###***Its my Fist time here***

In [ ]:
print('Glendah Moraa Nyabuto')

name

***i want to learn alot here***

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('/content/sample_data/california_housing_train.csv')
df

# Practice Makes Perfect

In [ ]:
df.shape

(17000, 9)

In [ ]:
df.head()

   longitude  latitude  ...  median_income  median_house_value
0    -114.31     34.19  ...         1.4936             66900.0
1    -114.47     34.40  ...         1.8200             80100.0
2    -114.56     33.69  ...         1.6509             85700.0
3    -114.57     33.64  ...         3.1917             73400.0
4    -114.57     33.57  ...         1.9250             65500.0

[5 rows x 9 columns]

In [ ]:
df.tail()

       longitude  latitude  ...  median_income  median_house_value
16995    -124.26     40.58  ...         2.3571            111400.0
16996    -124.27     40.69  ...         2.5179             79000.0
16997    -124.30     41.84  ...         3.0313            103600.0
16998    -124.30     41.80  ...         1.9797             85800.0
16999    -124.35     40.54  ...         3.0147             94600.0

[5 rows x 9 columns]

In [ ]:
df.set_index('latitude', inplace=True)

In [ ]:
df.loc[41.84]

longitude               -124.3000
housing_median_age        17.0000
total_rooms             2677.0000
total_bedrooms           531.0000
population              1244.0000
households               456.0000
median_income              3.0313
median_house_value    103600.0000
Name: 41.84, dtype: float64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Float64Index: 17000 entries, 34.19 to 40.54
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   housing_median_age  17000 non-null  float64
 2   total_rooms         17000 non-null  float64
 3   total_bedrooms      17000 non-null  float64
 4   population          17000 non-null  float64
 5   households          17000 non-null  float64
 6   median_income       17000 non-null  float64
 7   median_house_value  17000 non-null  float64
dtypes: float64(8)
memory usage: 1.8 MB

In [ ]:
df.dtypes

longitude             float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
dtype: object

In [ ]:
df.describe()

          longitude  housing_median_age  ...  median_income  median_house_value
count  17000.000000        17000.000000  ...   17000.000000        17000.000000
mean    -119.562108           28.589353  ...       3.883578       207300.912353
std        2.005166           12.586937  ...       1.908157       115983.764387
min     -124.350000            1.000000  ...       0.499900        14999.000000
25%     -121.790000           18.000000  ...       2.566375       119400.000000
50%     -118.490000           29.000000  ...       3.544600       180400.000000
75%     -118.000000           37.000000  ...       4.767000       265000.000000
max     -114.310000           52.000000  ...      15.000100       500001.000000

[8 rows x 8 columns]