# **SQL IP**

## **1.1 CONNECTING TO OUR DATABASE**

In [3]:
# We will first load the sql extension into our environment
%load_ext sql

# Then connect to our in memory sqlite database
# NB: This database will cease to exist as soon as the database connection is closed. 
%sql sqlite://

'Connected: @None'

In [4]:
# Import Pandas
import pandas as pd

## **1.2 LOADING OUR DATASET**

In [5]:
#Loading our GrandElectors Dataset

with open('GrandElectors_by_state (1).csv','r') as f:
    GrandElectors = pd.read_csv(f, index_col=0, encoding='utf-8')
%sql DROP TABLE if EXISTS GrandElectors;
%sql PERSIST GrandElectors;
%sql SELECT * FROM GrandElectors LIMIT 5;

 * sqlite://
Done.
 * sqlite://
 * sqlite://
Done.

[('Alabama', 9),
 ('Alaska', 3),
 ('Arizona', 11),
 ('Arkansas', 6),
 ('California', 55)]

In [6]:
#Loading our Population by state Dataset

with open('Population_by_state.csv','r') as f:
    Population = pd.read_csv(f, index_col=0, encoding='utf-8')
%sql DROP TABLE if EXISTS Population;
%sql PERSIST Population;
%sql SELECT * FROM Population LIMIT 5;

 * sqlite://
Done.
 * sqlite://
 * sqlite://
Done.

[('CALIFORNIA', 39144818),
 ('TEXAS', 27469114),
 ('FLORIDA', 20271272),
 ('NEW YORK', 19795791),
 ('ILLINOIS', 12859995)]

## **1.3 JOINING AND UPDATING**

In [7]:
#For us to be a ble to join the two table (GrandElectors and Population),
#we need to update the 'State' column on GrandElectors table to Uppercase 
#to match with the case used in 'State' column on the population table
#

%%sql
UPDATE GrandElectors
SET State = UPPER(State);

SELECT * FROM GrandElectors limit 10;

 * sqlite://
51 rows affected.
Done.

[('ALABAMA', 9),
 ('ALASKA', 3),
 ('ARIZONA', 11),
 ('ARKANSAS', 6),
 ('CALIFORNIA', 55),
 ('COLORADO', 9),
 ('CONNECTICUT', 7),
 ('DISTRICT OF COLUMBIA', 3),
 ('DELAWARE', 3),
 ('FLORIDA', 29)]

In [8]:
# Since the state columns in both tables are in the same format
# We can join the two tables to create a new tables using the key state
#

%%sql
CREATE TABLE IF NOT EXISTS Elects AS

SELECT GrandElectors.State, GrandElectors,  Population FROM GrandElectors INNER JOIN Population ON GrandElectors.State = Population.State

 * sqlite://
Done.

[]

In [9]:
#We can the use SELECT method to preview our new table GrandElectors_Population
#

%%sql
SELECT * FROM Elects limit 10;

 * sqlite://
Done.

[('ALABAMA', 9, 4858979),
 ('ALASKA', 3, 738432),
 ('ARIZONA', 11, 6828065),
 ('ARKANSAS', 6, 2978204),
 ('CALIFORNIA', 55, 39144818),
 ('COLORADO', 9, 5456574),
 ('CONNECTICUT', 7, 3590886),
 ('DISTRICT OF COLUMBIA', 3, 672228),
 ('DELAWARE', 3, 945934),
 ('FLORIDA', 29, 20271272)]

In [10]:
#Updating the column state where the state is DISTRICT OF COLUMBIA to 'DC'
#

%%sql
UPDATE Elects
SET State = 'DC'
WHERE State = 'DISTRICT OF COLUMBIA';

SELECT * FROM Elects limit 10;

 * sqlite://
1 rows affected.
Done.

[('ALABAMA', 9, 4858979),
 ('ALASKA', 3, 738432),
 ('ARIZONA', 11, 6828065),
 ('ARKANSAS', 6, 2978204),
 ('CALIFORNIA', 55, 39144818),
 ('COLORADO', 9, 5456574),
 ('CONNECTICUT', 7, 3590886),
 ('DC', 3, 672228),
 ('DELAWARE', 3, 945934),
 ('FLORIDA', 29, 20271272)]

## **1.4 FINDING THE RATIO**

In [11]:
#compute the ratio between the number of grand electors and the population. 
#Please create a new column with that ratio.
# lets save the the 
#
%%sql
CREATE TABLE Ratio_Table AS

SELECT State, GrandElectors, Population, ((GrandElectors * 50000000) / Population) AS GP_Ratio FROM Elects

 * sqlite://
Done.

[]

In [12]:
# Previewing the table Ratio_Table
#
%%sql
SELECT * FROM Ratio_Table

 * sqlite://
Done.

[('ALABAMA', 9, 4858979, 92),
 ('ALASKA', 3, 738432, 203),
 ('ARIZONA', 11, 6828065, 80),
 ('ARKANSAS', 6, 2978204, 100),
 ('CALIFORNIA', 55, 39144818, 70),
 ('COLORADO', 9, 5456574, 82),
 ('CONNECTICUT', 7, 3590886, 97),
 ('DC', 3, 672228, 223),
 ('DELAWARE', 3, 945934, 158),
 ('FLORIDA', 29, 20271272, 71),
 ('GEORGIA', 16, 10214860, 78),
 ('HAWAII', 4, 1431603, 139),
 ('IDAHO', 4, 1654930, 120),
 ('ILLINOIS', 20, 12859995, 77),
 ('INDIANA', 11, 6619680, 83),
 ('IOWA', 6, 3123899, 96),
 ('KANSAS', 6, 2911641, 103),
 ('KENTUCKY', 8, 4425092, 90),
 ('LOUISIANA', 8, 4670724, 85),
 ('MAINE', 4, 1329328, 150),
 ('MARYLAND', 10, 6006401, 83),
 ('MASSACHUSETTS', 11, 6794422, 80),
 ('MICHIGAN', 16, 9922576, 80),
 ('MINNESOTA', 10, 5489594, 91),
 ('MISSISSIPPI', 6, 2992333, 100),
 ('MISSOURI', 10, 6083672, 82),
 ('MONTANA', 3, 1032949, 145),
 ('NEBRASKA', 5, 1896190, 131),
 ('NEVADA', 6, 2890845, 103),
 ('NEW HAMPSHIRE', 4, 1330608, 150),
 ('NEW JERSEY', 14, 8958013, 78),
 ('NEW MEXICO', 5, 2085109, 119),
 ('NEW YORK', 29, 19795791, 73),
 ('NORTH CAROLINA', 15, 10042802, 74),
 ('NORTH DAKOTA', 3, 756927, 198),
 ('OHIO', 18, 11613423, 77),
 ('OKLAHOMA', 7, 3911338, 89),
 ('OREGON', 7, 4028977, 86),
 ('PENNSYLVANIA', 20, 12802503, 78),
 ('RHODE ISLAND', 4, 1056298, 189),
 ('SOUTH CAROLINA', 9, 4896146, 91),
 ('SOUTH DAKOTA', 3, 858469, 174),
 ('TENNESSEE', 11, 6600299, 83),
 ('TEXAS', 38, 27469114, 69),
 ('UTAH', 6, 2995919, 100),
 ('VERMONT', 3, 626042, 239),
 ('VIRGINIA', 13, 8382993, 77),
 ('WASHINGTON', 12, 7170351, 83),
 ('WEST VIRGINIA', 5, 1844128, 135),
 ('WISCONSIN', 10, 5771337, 86),
 ('WYOMING', 3, 586107, 255)]

In [13]:
#order the states by decreasing ratio of Grand Electors per capita. 
#That will make our priority list.
#
%%sql
SELECT * FROM Ratio_Table
ORDER BY GP_Ratio DESC

 * sqlite://
Done.

[('WYOMING', 3, 586107, 255),
 ('VERMONT', 3, 626042, 239),
 ('DC', 3, 672228, 223),
 ('ALASKA', 3, 738432, 203),
 ('NORTH DAKOTA', 3, 756927, 198),
 ('RHODE ISLAND', 4, 1056298, 189),
 ('SOUTH DAKOTA', 3, 858469, 174),
 ('DELAWARE', 3, 945934, 158),
 ('MAINE', 4, 1329328, 150),
 ('NEW HAMPSHIRE', 4, 1330608, 150),
 ('MONTANA', 3, 1032949, 145),
 ('HAWAII', 4, 1431603, 139),
 ('WEST VIRGINIA', 5, 1844128, 135),
 ('NEBRASKA', 5, 1896190, 131),
 ('IDAHO', 4, 1654930, 120),
 ('NEW MEXICO', 5, 2085109, 119),
 ('KANSAS', 6, 2911641, 103),
 ('NEVADA', 6, 2890845, 103),
 ('ARKANSAS', 6, 2978204, 100),
 ('MISSISSIPPI', 6, 2992333, 100),
 ('UTAH', 6, 2995919, 100),
 ('CONNECTICUT', 7, 3590886, 97),
 ('IOWA', 6, 3123899, 96),
 ('ALABAMA', 9, 4858979, 92),
 ('MINNESOTA', 10, 5489594, 91),
 ('SOUTH CAROLINA', 9, 4896146, 91),
 ('KENTUCKY', 8, 4425092, 90),
 ('OKLAHOMA', 7, 3911338, 89),
 ('OREGON', 7, 4028977, 86),
 ('WISCONSIN', 10, 5771337, 86),
 ('LOUISIANA', 8, 4670724, 85),
 ('INDIANA', 11, 6619680, 83),
 ('MARYLAND', 10, 6006401, 83),
 ('TENNESSEE', 11, 6600299, 83),
 ('WASHINGTON', 12, 7170351, 83),
 ('COLORADO', 9, 5456574, 82),
 ('MISSOURI', 10, 6083672, 82),
 ('ARIZONA', 11, 6828065, 80),
 ('MASSACHUSETTS', 11, 6794422, 80),
 ('MICHIGAN', 16, 9922576, 80),
 ('GEORGIA', 16, 10214860, 78),
 ('NEW JERSEY', 14, 8958013, 78),
 ('PENNSYLVANIA', 20, 12802503, 78),
 ('ILLINOIS', 20, 12859995, 77),
 ('OHIO', 18, 11613423, 77),
 ('VIRGINIA', 13, 8382993, 77),
 ('NORTH CAROLINA', 15, 10042802, 74),
 ('NEW YORK', 29, 19795791, 73),
 ('FLORIDA', 29, 20271272, 71),
 ('CALIFORNIA', 55, 39144818, 70),
 ('TEXAS', 38, 27469114, 69)]

## **1.5.COMPUTING RUNNING TOTAL**

In [14]:
#compute the running total of Grand Electors in that sorted list
#Create a table
#

%%sql
CREATE TABLE Running_Total AS 
SELECT a1.State, a1.GrandElectors, SUM(a2.GrandElectors)Cumulative
FROM Ratio_Table a1, Ratio_Table a2
WHERE a1.GrandElectors <= a2.GrandElectors OR (a1.GrandElectors = a2.GrandElectors AND a1.State = a2.State)
GROUP BY a1.State, a1.GrandElectors
ORDER BY a1.GP_Ratio DESC, a1.State DESC

 * sqlite://
Done.

[]

In [15]:
%%sql

SELECT * FROM Running_Total

 * sqlite://
Done.

[('WYOMING', 3, 538),
 ('VERMONT', 3, 538),
 ('DC', 3, 538),
 ('ALASKA', 3, 538),
 ('NORTH DAKOTA', 3, 538),
 ('RHODE ISLAND', 4, 514),
 ('SOUTH DAKOTA', 3, 538),
 ('DELAWARE', 3, 538),
 ('NEW HAMPSHIRE', 4, 514),
 ('MAINE', 4, 514),
 ('MONTANA', 3, 538),
 ('HAWAII', 4, 514),
 ('WEST VIRGINIA', 5, 494),
 ('NEBRASKA', 5, 494),
 ('IDAHO', 4, 514),
 ('NEW MEXICO', 5, 494),
 ('NEVADA', 6, 479),
 ('KANSAS', 6, 479),
 ('UTAH', 6, 479),
 ('MISSISSIPPI', 6, 479),
 ('ARKANSAS', 6, 479),
 ('CONNECTICUT', 7, 443),
 ('IOWA', 6, 479),
 ('ALABAMA', 9, 406),
 ('SOUTH CAROLINA', 9, 406),
 ('MINNESOTA', 10, 379),
 ('KENTUCKY', 8, 422),
 ('OKLAHOMA', 7, 443),
 ('WISCONSIN', 10, 379),
 ('OREGON', 7, 443),
 ('LOUISIANA', 8, 422),
 ('WASHINGTON', 12, 295),
 ('TENNESSEE', 11, 339),
 ('MARYLAND', 10, 379),
 ('INDIANA', 11, 339),
 ('MISSOURI', 10, 379),
 ('COLORADO', 9, 406),
 ('MICHIGAN', 16, 241),
 ('MASSACHUSETTS', 11, 339),
 ('ARIZONA', 11, 339),
 ('PENNSYLVANIA', 20, 191),
 ('NEW JERSEY', 14, 270),
 ('GEORGIA', 16, 241),
 ('VIRGINIA', 13, 283),
 ('OHIO', 18, 209),
 ('ILLINOIS', 20, 191),
 ('NORTH CAROLINA', 15, 256),
 ('NEW YORK', 29, 151),
 ('FLORIDA', 29, 151),
 ('CALIFORNIA', 55, 55),
 ('TEXAS', 38, 93)]

In [16]:
#Independently, to compute the half of the total of Grand Electors overall (in the whole country):
#This is the threshold we need to reach for winning the presidential electioN
#

%%sql
SELECT  MAX(Cumulative) / 2+1 FROM Running_Total

 * sqlite://
Done.

[(270,)]

In [17]:
#Select all the states for which the running total is below or equal to the threshold
#

%%sql
SELECT State FROM Running_Total
WHERE Cumulative >  270
ORDER BY Cumulative

 * sqlite://
Done.

[('VIRGINIA',),
 ('WASHINGTON',),
 ('TENNESSEE',),
 ('INDIANA',),
 ('MASSACHUSETTS',),
 ('ARIZONA',),
 ('MINNESOTA',),
 ('WISCONSIN',),
 ('MARYLAND',),
 ('MISSOURI',),
 ('ALABAMA',),
 ('SOUTH CAROLINA',),
 ('COLORADO',),
 ('KENTUCKY',),
 ('LOUISIANA',),
 ('CONNECTICUT',),
 ('OKLAHOMA',),
 ('OREGON',),
 ('NEVADA',),
 ('KANSAS',),
 ('UTAH',),
 ('MISSISSIPPI',),
 ('ARKANSAS',),
 ('IOWA',),
 ('WEST VIRGINIA',),
 ('NEBRASKA',),
 ('NEW MEXICO',),
 ('RHODE ISLAND',),
 ('NEW HAMPSHIRE',),
 ('MAINE',),
 ('HAWAII',),
 ('IDAHO',),
 ('WYOMING',),
 ('VERMONT',),
 ('DC',),
 ('ALASKA',),
 ('NORTH DAKOTA',),
 ('SOUTH DAKOTA',),
 ('DELAWARE',),
 ('MONTANA',)]